before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/xyz2ogc/
    binary: xyz2ogc
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - name_template: >-
      {{ .ProjectName }}-
      {{- .Os }}-
      {{- .Arch }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  use: github-native
brews:
  - tap:
      owner: planetlabs
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/planetlabs/{{ .ProjectName }}/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/planetlabs/go-ogc"
    description: "Generate OGC API - Tiles metadata from exiting XYZ tilesets."
    license: "Apache-2.0"
    test: |
      system "#{bin}/xyz2ogc version"
