name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5.4.0
        with:
          go-version: '1.20'
      - uses: golangci/golangci-lint-action@v8
        with:
          version: v1.51.2
          args: "--out-${NO_FUTURE}format colored-line-number"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5.4.0
        with:
          go-version: '1.20'
      - run: go test -v ./...
